// Shared modern styles for card grids
export const cardGridStyles = {
  container: {
    marginTop: '2rem',
  },
  title: {
    fontSize: '1.8rem',
    fontWeight: '700',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    marginBottom: '1.5rem',
  } as React.CSSProperties,
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
    gap: '1.5rem',
    marginTop: '1.5rem',
  },
  card: {
    backgroundColor: 'rgba(42, 42, 62, 0.6)',
    backdropFilter: 'blur(10px)',
    borderRadius: '16px',
    padding: '1.25rem',
    textAlign: 'center' as const,
    display: 'flex',
    flexDirection: 'column' as const,
    border: '1px solid rgba(100, 108, 255, 0.1)',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.2)',
  },
  cardHover: {
    transform: 'translateY(-8px)',
    boxShadow: '0 12px 40px rgba(100, 108, 255, 0.3)',
    borderColor: 'rgba(100, 108, 255, 0.4)',
  },
  cardImage: {
    width: '100%',
    height: 'auto',
    borderRadius: '12px',
    boxShadow: '0 4px 16px rgba(0, 0, 0, 0.3)',
  },
  cardName: {
    marginTop: '0.75rem',
    fontWeight: '600',
    fontSize: '1rem',
    color: '#fff',
  },
  cardId: {
    fontSize: '0.9rem',
    color: '#a0a0c0',
    marginBottom: '0.75rem',
  },
  buttonContainer: {
    display: 'flex',
    gap: '0.5rem',
    marginTop: 'auto',
    justifyContent: 'center',
  },
  button: (isActive: boolean, color: string) => ({
    flex: 1,
    padding: '0.6rem',
    backgroundColor: isActive ? color : 'rgba(42, 42, 62, 0.8)',
    color: 'white',
    border: `1px solid ${isActive ? color : 'rgba(100, 108, 255, 0.2)'}`,
    borderRadius: '8px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.3rem',
    fontSize: '0.85rem',
    fontWeight: '500',
    transition: 'all 0.3s ease',
    boxShadow: isActive
      ? `0 4px 12px ${color}40`
      : '0 2px 8px rgba(0, 0, 0, 0.2)',
  }),
  emptyState: {
    color: '#a0a0c0',
    textAlign: 'center' as const,
    marginTop: '4rem',
    fontSize: '1.1rem',
    padding: '3rem',
    backgroundColor: 'rgba(42, 42, 62, 0.4)',
    borderRadius: '16px',
    border: '1px dashed rgba(100, 108, 255, 0.3)',
  },
};
