// Shared modern styles for card grids
export const cardGridStyles = {
  container: {
    marginTop: '2rem',
  },
  title: {
    fontSize: '1.8rem',
    fontWeight: '700',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    marginBottom: '1.5rem',
  } as React.CSSProperties,
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))',
    gap: '1rem',
    marginTop: '1.5rem',
  },
  card: {
    backgroundColor: 'rgba(42, 42, 62, 0.6)',
    backdropFilter: 'blur(10px)',
    borderRadius: '12px',
    padding: '0.75rem',
    textAlign: 'center' as const,
    display: 'flex',
    flexDirection: 'column' as const,
    border: '1px solid rgba(100, 108, 255, 0.1)',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.2)',
    position: 'relative' as const,
  },
  cardHover: {
    transform: 'translateY(-6px)',
    boxShadow: '0 12px 40px rgba(100, 108, 255, 0.3)',
    borderColor: 'rgba(100, 108, 255, 0.4)',
  },
  cardImage: {
    width: '100%',
    height: 'auto',
    borderRadius: '8px',
    boxShadow: '0 4px 16px rgba(0, 0, 0, 0.3)',
  },
  cardName: {
    marginTop: '0.5rem',
    fontWeight: '600',
    fontSize: '0.85rem',
    color: '#fff',
    lineHeight: '1.2',
  },
  cardId: {
    fontSize: '0.75rem',
    color: '#a0a0c0',
    marginTop: '0.25rem',
  },
  buttonContainer: {
    position: 'absolute' as const,
    top: '0.5rem',
    right: '0.5rem',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.4rem',
    opacity: 0,
    transition: 'opacity 0.3s ease',
  },
  button: (isActive: boolean, color: string) => ({
    padding: '0.4rem',
    backgroundColor: isActive ? `${color}dd` : 'rgba(0, 0, 0, 0.7)',
    color: 'white',
    border: `1px solid ${isActive ? color : 'rgba(255, 255, 255, 0.3)'}`,
    borderRadius: '6px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.75rem',
    fontWeight: '500',
    transition: 'all 0.3s ease',
    boxShadow: isActive
      ? `0 2px 8px ${color}60`
      : '0 2px 8px rgba(0, 0, 0, 0.4)',
    backdropFilter: 'blur(10px)',
    width: '32px',
    height: '32px',
  }),
  emptyState: {
    color: '#a0a0c0',
    textAlign: 'center' as const,
    marginTop: '4rem',
    fontSize: '1.1rem',
    padding: '3rem',
    backgroundColor: 'rgba(42, 42, 62, 0.4)',
    borderRadius: '16px',
    border: '1px dashed rgba(100, 108, 255, 0.3)',
  },
};
